### ISSUE TITLE
How do I integrate this package into KeyCloak?

### ISSUE THREAD

**Issue by brucelpt** [rishabhsvats/keycloak-conditional-role-prefix-authenticator#1]
My KeyCloak Version is  19.0.1.
I don't know how to integrate this JAR package into KeyCloak. Could you please elaborate on this?

**Comment by brucelpt** [comment]
HI rishabhsvats!
     I'm learning Keycloak and we have some custom requirements for custom authentication.I read the certified SPI documentation for Keycloak(https://www.keycloak.org/docs/latest/server_development/#_auth_spi).
     However, he didn't specify how to integrate the examples in the source code into Keycloak. I just read your documentation and code, so how do I integrate your project into Keycloak?The Keycloak version can be 18.x or 19.0.1.

**Comment by rishabhsvats** [comment]
Hello @brucelpt 

I am assuming you are using Quarkus distribution of Keycloak.

To install the jar , you need to place the jar in keycloak-installation-dir/providers/ and then run bin/kc.[sh|bat] build. Refer : https://www.keycloak.org/docs/latest/server_development/#packaging-and-deployment

**Comment by brucelpt** [comment]
收到谢谢配合

**Comment by brucelpt** [comment]
Hello,rishabhsvats
I have put the JAR package into the Provider directory, and run command ${kc.home.dir}/bin/kc.sh build
,and then i restart the service. 
![image](https://user-images.githubusercontent.com/37991444/184296982-6d5029bd-6080-437b-ab21-9eef11d800bc.png)
![image](https://user-images.githubusercontent.com/37991444/184297014-634686b4-79b2-4dbc-b6cd-360008518888.png)

Meanwhile, I have integrated the official secretQuestion example of Keycloak. I can see the Secret Question on the adding page, but I can't find your Role Check Or conditional_role_prefix option.
![image](https://user-images.githubusercontent.com/37991444/184297073-e041f8cb-b810-4399-8f4f-8d966ca96d94.png)

By the way, my Keycloak version is V19.0.1. I noticed that the image UI style in your use case is not the latest version. Is it because of version compatibility that I can't import your use case?

**Comment by rishabhsvats** [comment]
Hello @brucelpt

Could you check by adding condition through "Add Condition" , adding reference screenshot: (Condition - role prefix)

![image](https://user-images.githubusercontent.com/25544307/184579155-72d43d5d-0bbd-48df-8cf4-2590686fa10c.png)

![image](https://user-images.githubusercontent.com/25544307/184578956-7f069384-be26-4142-ac47-6f126a9a11b9.png)

**Comment by brucelpt** [comment]
收到谢谢配合
