### ISSUE TITLE
Help please, i have a huge doubt/question/dilemma

### ISSUE THREAD

**Issue by gaetanolb** [rishabhsvats/keycloak-conditional-role-prefix-authenticator#2]
Hi friend.
We are using Keycloak Widfly. The steps performed are as follows:
A. We replicated your authentication flow (screen):
![image](https://user-images.githubusercontent.com/67560677/192756513-bbdffd02-8b55-42d7-bf78-e75013f928fd.png)

B. We created an Authenticator client with an XYZ_ADMIN role (screen):
![image](https://user-images.githubusercontent.com/67560677/192756758-7e46a122-6e7d-490a-bca7-645e9d619fd2.png)

Only the user "know" has this role (screen):
![image](https://user-images.githubusercontent.com/67560677/192756890-ece7319e-3c3e-4ac2-9173-5edf43df4b09.png)

C. We defined 3 users:
![image](https://user-images.githubusercontent.com/67560677/192757166-89f7eca6-549c-4fec-9b2d-7f51fce48b6e.png)

Users "bambi", "chicco" and "allo" do not have that role, so they should not be able to log in. Unfortunately they do access with POSTMAN :((((((((( ....... 
![image](https://user-images.githubusercontent.com/67560677/192757692-81424a8c-4936-4e98-8be5-f54a027004b7.png)

THANK YOU

**Comment by rishabhsvats** [comment]
Hello @gaetanolb 
 
I understand that you are unable to restrict users on the basis of Conditional Role authenticator, when using Postman.

As per the shared screenshot when using Postman, it seems you are using "clients" authentication flow. The "clients" authentication flow might be the default one.

The flow can be looked at Authentication --> Flow --> clients
